### ISSUE TITLE
Failed to save span - plugin error

### ISSUE THREAD

**Issue by srikanthccv** [muhammadn/jaeger-s3#56]
Hi @muhammadn ,

I am running into a unknown error while trying to using the s3 plugin. Here the log output.

```sh
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: GRPC_STORAGE_PLUGIN_BINARY=./jaeger-s3
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: GRPC_STORAGE_PLUGIN_CONFIGURATION_FILE=./jaeger-s3-config.yaml
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: GRPC_STORAGE_PLUGIN_LOG_LEVEL=DEBUG
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: HISTCONTROL=ignoredups
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: HISTSIZE=1000
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: HOME=/home/ec2-user
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: HOSTNAME=ip-172-31-86-8.ec2.internal
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: LANG=en_US.UTF-8
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: LC_CTYPE=UTF-8
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: LESSOPEN=||/usr/bin/lesspipe.sh %s
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: LOGNAME=ec2-user
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: LS_COLORS=rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: MAIL=/var/spool/mail/ec2-user
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: PLUGIN_MAX_PORT=25000
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: PLUGIN_MIN_PORT=10000
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: PLUGIN_PROTOCOL_VERSIONS=1
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: PWD=/home/ec2-user
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: SHELL=/bin/bash
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: SHLVL=1
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: SPAN_STORAGE_TYPE=grpc-plugin
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: SSH_CLIENT=115.98.144.209 56884 22
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: SSH_CONNECTION=115.98.144.209 56884 172.31.86.8 22
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: SSH_TTY=/dev/pts/1
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: STORAGE_PLUGIN=jaeger
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: TERM=xterm-256color
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: USER=ec2-user
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: XDG_RUNTIME_DIR=/run/user/1000
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: XDG_SESSION_ID=408
2022-04-10T19:17:41.109Z [DEBUG] jaeger-s3: 2022-04-10T19:17:41.109Z [WARN]  jaeger-s3: _=./jaeger-1.32.0-linux-amd64/jaeger-all-in-one
2022-04-10T19:17:46.090Z [DEBUG] jaeger-s3: 2022/04/10 19:17:46 chunkStore error: %s error creating index client: timeout
2022-04-10T19:17:46.091Z [DEBUG] jaeger-s3: plugin address: address=/tmp/plugin1069606534 network=unix timestamp=2022-04-10T19:17:46.091Z
2022-04-10T19:17:46.091Z [DEBUG] using plugin: version=1
...
...
{"level":"info","ts":1649618266.1095,"caller":"grpclog/component.go:71","msg":"[core]pickfirstBalancer: UpdateSubConnState: 0xc00003b5a0, {CONNECTING <nil>}","system":"grpc","grpc_log":true}
{"level":"info","ts":1649618266.1095133,"caller":"channelz/logging.go:50","msg":"[core]Channel Connectivity change to CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1649618266.1097538,"caller":"channelz/logging.go:50","msg":"[core]Subchannel Connectivity change to READY","system":"grpc","grpc_log":true}
{"level":"info","ts":1649618266.109787,"caller":"grpclog/component.go:71","msg":"[core]pickfirstBalancer: UpdateSubConnState: 0xc00003b5a0, {READY <nil>}","system":"grpc","grpc_log":true}
{"level":"info","ts":1649618266.1098506,"caller":"channelz/logging.go:50","msg":"[core]Channel Connectivity change to READY","system":"grpc","grpc_log":true}
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: panic: runtime error: invalid memory address or nil pointer dereference
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: [signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x15156b2]
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3:
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: goroutine 104 [running]:
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: github.com/grafana/loki/pkg/storage.(*store).PutOne(0xc00038a400, {0x1cb0bd0, 0xc0002d4870}, 0x1, 0x1, {0x984aba14057664d3, {0x19b7a57, 0x4}, 0x18014e92bd0, 0x18014e92bd0, ...})
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: 	<autogenerated>:1 +0x52
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: jaeger-s3/s3store.(*Writer).WriteSpan(0xc0000a0480, 0xc000170870)
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: 	/Users/zaihan/Projects/jaeger-s3/s3store/writer.go:155 +0x683
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: github.com/jaegertracing/jaeger/plugin/storage/grpc/shared.(*grpcServer).WriteSpan(0x1906420, {0xc0002d5bc0, 0x50f166}, 0xc0002d5bc0)
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: 	/Users/zaihan/Projects/go/pkg/mod/github.com/jaegertracing/jaeger@v1.17.1/plugin/storage/grpc/shared/grpc_server.go:46 +0x3a
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: github.com/jaegertracing/jaeger/proto-gen/storage_v1._SpanWriterPlugin_WriteSpan_Handler({0x187e6e0, 0xc000442270}, {0x1cb0bd0, 0xc0002d5b90}, 0xc0000a0f60, 0x0)
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: 	/Users/zaihan/Projects/go/pkg/mod/github.com/jaegertracing/jaeger@v1.17.1/proto-gen/storage_v1/storage.pb.go:950 +0x170
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00015a1a0, {0x1cd34e0, 0xc000312600}, 0xc0000c4d00, 0xc0002d5200, 0x2a28040, 0x0)
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: 	/Users/zaihan/Projects/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0xc8f
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: google.golang.org/grpc.(*Server).handleStream(0xc00015a1a0, {0x1cd34e0, 0xc000312600}, 0xc0000c4d00, 0x0)
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: 	/Users/zaihan/Projects/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0x9f3
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: google.golang.org/grpc.(*Server).serveStreams.func1.1()
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: 	/Users/zaihan/Projects/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0x98
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-04-10T19:17:47.093Z [DEBUG] jaeger-s3: 	/Users/zaihan/Projects/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xef
{"level":"info","ts":1649618267.0946355,"caller":"channelz/logging.go:50","msg":"[core]Subchannel Connectivity change to IDLE","system":"grpc","grpc_log":true}
2022-04-10T19:17:47.094Z [DEBUG] plugin process exited: path=./jaeger-s3 pid=20316 error="exit status 2"
{"level":"info","ts":1649618267.0947556,"caller":"grpclog/component.go:71","msg":"[core]pickfirstBalancer: UpdateSubConnState: 0xc00003a4a0, {IDLE <nil>}","system":"grpc","grpc_log":true}
{"level":"info","ts":1649618267.0947843,"caller":"channelz/logging.go:50","msg":"[core]Channel Connectivity change to IDLE","system":"grpc","grpc_log":true}
{"level":"error","ts":1649618267.0948224,"caller":"app/span_processor.go:149","msg":"Failed to save span","error":"plugin error: rpc error: code = Unavailable desc = error reading from server: read unix @->/tmp/plugin1069606534: read: connection reset by peer","stacktrace":"github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\tgithub.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:149\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\tgithub.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:35\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\tgithub.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:179\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\tgithub.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:76\ngithub.com/jaegertracing/jaeger/pkg/queue.ConsumerFunc.Consume\n\tgithub.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:104\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumersWithFactory.func1\n\tgithub.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:83"}
```

And here is what my config looks like.

```yaml
schema_config:
  configs:
    - from: 2022-04-07
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
      row_shards: 10

storage_config:
  aws:
    bucketnames: <my_bucket_name>
    region: us-east-1
    access_key_id: <my_ access_key_id >
    secret_access_key: <my_ secret_access_key >
    endpoint: s3.us-east-1.amazonaws.com
    http_config:
      idle_conn_timeout: 120s
      response_header_timeout: 60s
  boltdb_shipper:
    active_index_directory: /tmp/loki/boltdb-shipper-active
    cache_location: /tmp/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: s3
  filesystem:
    directory: /tmp/loki/chunks

compactor:
  working_directory: /tmp/loki/boltdb-shipper-compactor
  shared_store: s3
```

What could I be doing wrong in this? Or is it some issue with the plugin?

**Comment by muhammadn** [comment]
@srikanthccv I cannot reproduce your error. Usually this means there is a problem with your s3 configuration.

can you try to change this part:

```
  aws:
    access_key_id: <my_ access_key_id >
    secret_access_key: <my_ secret_access_key >
    s3: s3://us-east-1/yourbucket
    http_config:
      idle_conn_timeout: 120s
      response_header_timeout: 60s
```
